config/routes.rb
IntroPractica::Application.routes.draw do
  resources :users

  resources :contacts do
    member do
      get :unsubscribe
    end
    
    collection do
      get :active
    end
  end

  root :to => "welcome#index"
  match 'about' => 'welcome#about'
  match "admin" => "users#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates :name, :presence => true
  validates :sex, :presence => true
  
  scope :active, where(:newsletter => true)
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        UserMailer.welcome(@contact).deliver
        format.html { redirect_to(@contact, :notice => t(:send_contact) ) }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'Contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end
  
  def unsubscribe
    @contact = Contact.find(params[:id])
  end
  
  def active
    @contacts = Contact.active
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :authenticate, :only => :show

layout "admin"

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

private
	def authenticate
	user = User.find(params[:id])
		if user.first_name == "Misterioso"
		redirect_to root_path, :notice => "Acceso restringido"
		end
	end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def name(user)
		"#{user.first_name} #{user.last_name}"
	end 

     	def alter_column_css(index)
	    index % 2 == 0 ? "dark" : "light"
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_contact.html.erb
<tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.newsletter %></td>
    <td><%= contact.sex %></td>
    <td><%= contact.notes %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Unsubscribe', unsubscribe_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

app/views/contacts/_form.html.erb
<%= form_for @contact, :html => {:class => "form_class"} do |f| %>

<%= render :partial => "shared/errors", :locals => { :form => @contact } %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 20 %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :size => 20 %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :newsletter %><br />
    <%= f.check_box :newsletter, :checked => (@contact.newsletter ? true : false)  %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.select :sex, ['Male', 'Female'], :include_blank => true %> 
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :size => "29x50" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/active.html.erb
<h1>Active contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Newsletter</th>
    <th>Sex</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>

<%= render :partial => "contact", :locals => { :contact => contact } %>

<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

<br />

<%= link_to 'Contacts', contacts_path %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Newsletter</th>
    <th>Sex</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
<%= render :partial => "contact", :locals => { :contact => contact } %>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

<br />

<%= link_to 'Active Contact', active_contacts_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Newsletter:</b>
  <%= @contact.newsletter %>
</p>

<p>
  <b>Sex:</b>
  <%= @contact.sex %>
</p>

<p>
  <b>Notes:</b>
  <%= @contact.notes %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/unsubscribe.html.erb
<h1>Unsubscribe</h1>

<%= form_for(@contact) do |f| %>

  <div class="field">
    <%= f.check_box :newsletter, :checked => true  %>
    <%= f.label :newsletter, "Uncheck this check box to stop receiving our newsletter" %>
  </div>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>

<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroPractica</title>
  <%= stylesheet_link_tag "admin" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<h1>Zona Admin</h1>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroPractica</title>
  <%= stylesheet_link_tag "bruno" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroPractica</title>
  <%= stylesheet_link_tag "email" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
  <% if form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_menu.html.erb
<div id="menu">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About us", about_path %></li>
		<li><%= link_to "Contact", contacts_path %></li>
	</ul> 
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<%= render :partial => "shared/errors", :locals => { :form => @user } %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Listing users</h2>

<table border="1" cellspadding="2">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each_with_index do |user,index| %>
  <tr class="<%= alter_column_css(index) %>">
    <td><%= name(user) %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<p><%= link_to 'New User', new_user_path %></p>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<h1>About</h1>

<%= image_tag("01.jpg", :mouseover => "/images/02.jpg") %>

app/views/welcome/index.html.erb
<h1><%=t :welcome %></h1>